// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package com.pb;

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MobilePhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MobilePhone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string brand = 1;</code>
     */
    boolean hasBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>required .HardWare hardWare = 2;</code>
     */
    boolean hasHardWare();
    /**
     * <code>required .HardWare hardWare = 2;</code>
     */
    com.pb.Mobile.HardWare getHardWare();
    /**
     * <code>required .HardWare hardWare = 2;</code>
     */
    com.pb.Mobile.HardWareOrBuilder getHardWareOrBuilder();

    /**
     * <code>repeated string software = 3;</code>
     */
    java.util.List<java.lang.String>
        getSoftwareList();
    /**
     * <code>repeated string software = 3;</code>
     */
    int getSoftwareCount();
    /**
     * <code>repeated string software = 3;</code>
     */
    java.lang.String getSoftware(int index);
    /**
     * <code>repeated string software = 3;</code>
     */
    com.google.protobuf.ByteString
        getSoftwareBytes(int index);
  }
  /**
   * Protobuf type {@code MobilePhone}
   */
  public  static final class MobilePhone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MobilePhone)
      MobilePhoneOrBuilder {
    // Use MobilePhone.newBuilder() to construct.
    private MobilePhone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MobilePhone() {
      brand_ = "";
      software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MobilePhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              brand_ = bs;
              break;
            }
            case 18: {
              com.pb.Mobile.HardWare.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = hardWare_.toBuilder();
              }
              hardWare_ = input.readMessage(com.pb.Mobile.HardWare.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hardWare_);
                hardWare_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                software_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              software_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = software_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pb.Mobile.internal_static_MobilePhone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pb.Mobile.internal_static_MobilePhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pb.Mobile.MobilePhone.class, com.pb.Mobile.MobilePhone.Builder.class);
    }

    private int bitField0_;
    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object brand_;
    /**
     * <code>required string brand = 1;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWARE_FIELD_NUMBER = 2;
    private com.pb.Mobile.HardWare hardWare_;
    /**
     * <code>required .HardWare hardWare = 2;</code>
     */
    public boolean hasHardWare() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .HardWare hardWare = 2;</code>
     */
    public com.pb.Mobile.HardWare getHardWare() {
      return hardWare_ == null ? com.pb.Mobile.HardWare.getDefaultInstance() : hardWare_;
    }
    /**
     * <code>required .HardWare hardWare = 2;</code>
     */
    public com.pb.Mobile.HardWareOrBuilder getHardWareOrBuilder() {
      return hardWare_ == null ? com.pb.Mobile.HardWare.getDefaultInstance() : hardWare_;
    }

    public static final int SOFTWARE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList software_;
    /**
     * <code>repeated string software = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSoftwareList() {
      return software_;
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public int getSoftwareCount() {
      return software_.size();
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public java.lang.String getSoftware(int index) {
      return software_.get(index);
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSoftwareBytes(int index) {
      return software_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHardWare()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHardWare().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getHardWare());
      }
      for (int i = 0; i < software_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, software_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHardWare());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < software_.size(); i++) {
          dataSize += computeStringSizeNoTag(software_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSoftwareList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pb.Mobile.MobilePhone)) {
        return super.equals(obj);
      }
      com.pb.Mobile.MobilePhone other = (com.pb.Mobile.MobilePhone) obj;

      boolean result = true;
      result = result && (hasBrand() == other.hasBrand());
      if (hasBrand()) {
        result = result && getBrand()
            .equals(other.getBrand());
      }
      result = result && (hasHardWare() == other.hasHardWare());
      if (hasHardWare()) {
        result = result && getHardWare()
            .equals(other.getHardWare());
      }
      result = result && getSoftwareList()
          .equals(other.getSoftwareList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBrand()) {
        hash = (37 * hash) + BRAND_FIELD_NUMBER;
        hash = (53 * hash) + getBrand().hashCode();
      }
      if (hasHardWare()) {
        hash = (37 * hash) + HARDWARE_FIELD_NUMBER;
        hash = (53 * hash) + getHardWare().hashCode();
      }
      if (getSoftwareCount() > 0) {
        hash = (37 * hash) + SOFTWARE_FIELD_NUMBER;
        hash = (53 * hash) + getSoftwareList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pb.Mobile.MobilePhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pb.Mobile.MobilePhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pb.Mobile.MobilePhone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MobilePhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MobilePhone)
        com.pb.Mobile.MobilePhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pb.Mobile.internal_static_MobilePhone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pb.Mobile.internal_static_MobilePhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pb.Mobile.MobilePhone.class, com.pb.Mobile.MobilePhone.Builder.class);
      }

      // Construct using com.pb.Mobile.MobilePhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHardWareFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hardWareBuilder_ == null) {
          hardWare_ = null;
        } else {
          hardWareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pb.Mobile.internal_static_MobilePhone_descriptor;
      }

      public com.pb.Mobile.MobilePhone getDefaultInstanceForType() {
        return com.pb.Mobile.MobilePhone.getDefaultInstance();
      }

      public com.pb.Mobile.MobilePhone build() {
        com.pb.Mobile.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pb.Mobile.MobilePhone buildPartial() {
        com.pb.Mobile.MobilePhone result = new com.pb.Mobile.MobilePhone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (hardWareBuilder_ == null) {
          result.hardWare_ = hardWare_;
        } else {
          result.hardWare_ = hardWareBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = software_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.software_ = software_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pb.Mobile.MobilePhone) {
          return mergeFrom((com.pb.Mobile.MobilePhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pb.Mobile.MobilePhone other) {
        if (other == com.pb.Mobile.MobilePhone.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          bitField0_ |= 0x00000001;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasHardWare()) {
          mergeHardWare(other.getHardWare());
        }
        if (!other.software_.isEmpty()) {
          if (software_.isEmpty()) {
            software_ = other.software_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSoftwareIsMutable();
            software_.addAll(other.software_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBrand()) {
          return false;
        }
        if (!hasHardWare()) {
          return false;
        }
        if (!getHardWare().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pb.Mobile.MobilePhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pb.Mobile.MobilePhone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object brand_ = "";
      /**
       * <code>required string brand = 1;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }

      private com.pb.Mobile.HardWare hardWare_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pb.Mobile.HardWare, com.pb.Mobile.HardWare.Builder, com.pb.Mobile.HardWareOrBuilder> hardWareBuilder_;
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public boolean hasHardWare() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public com.pb.Mobile.HardWare getHardWare() {
        if (hardWareBuilder_ == null) {
          return hardWare_ == null ? com.pb.Mobile.HardWare.getDefaultInstance() : hardWare_;
        } else {
          return hardWareBuilder_.getMessage();
        }
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public Builder setHardWare(com.pb.Mobile.HardWare value) {
        if (hardWareBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hardWare_ = value;
          onChanged();
        } else {
          hardWareBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public Builder setHardWare(
          com.pb.Mobile.HardWare.Builder builderForValue) {
        if (hardWareBuilder_ == null) {
          hardWare_ = builderForValue.build();
          onChanged();
        } else {
          hardWareBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public Builder mergeHardWare(com.pb.Mobile.HardWare value) {
        if (hardWareBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              hardWare_ != null &&
              hardWare_ != com.pb.Mobile.HardWare.getDefaultInstance()) {
            hardWare_ =
              com.pb.Mobile.HardWare.newBuilder(hardWare_).mergeFrom(value).buildPartial();
          } else {
            hardWare_ = value;
          }
          onChanged();
        } else {
          hardWareBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public Builder clearHardWare() {
        if (hardWareBuilder_ == null) {
          hardWare_ = null;
          onChanged();
        } else {
          hardWareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public com.pb.Mobile.HardWare.Builder getHardWareBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHardWareFieldBuilder().getBuilder();
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      public com.pb.Mobile.HardWareOrBuilder getHardWareOrBuilder() {
        if (hardWareBuilder_ != null) {
          return hardWareBuilder_.getMessageOrBuilder();
        } else {
          return hardWare_ == null ?
              com.pb.Mobile.HardWare.getDefaultInstance() : hardWare_;
        }
      }
      /**
       * <code>required .HardWare hardWare = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pb.Mobile.HardWare, com.pb.Mobile.HardWare.Builder, com.pb.Mobile.HardWareOrBuilder> 
          getHardWareFieldBuilder() {
        if (hardWareBuilder_ == null) {
          hardWareBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pb.Mobile.HardWare, com.pb.Mobile.HardWare.Builder, com.pb.Mobile.HardWareOrBuilder>(
                  getHardWare(),
                  getParentForChildren(),
                  isClean());
          hardWare_ = null;
        }
        return hardWareBuilder_;
      }

      private com.google.protobuf.LazyStringList software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSoftwareIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = new com.google.protobuf.LazyStringArrayList(software_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSoftwareList() {
        return software_.getUnmodifiableView();
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public int getSoftwareCount() {
        return software_.size();
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public java.lang.String getSoftware(int index) {
        return software_.get(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSoftwareBytes(int index) {
        return software_.getByteString(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder setSoftware(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addSoftware(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addAllSoftware(
          java.lang.Iterable<java.lang.String> values) {
        ensureSoftwareIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, software_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder clearSoftware() {
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addSoftwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MobilePhone)
    }

    // @@protoc_insertion_point(class_scope:MobilePhone)
    private static final com.pb.Mobile.MobilePhone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pb.Mobile.MobilePhone();
    }

    public static com.pb.Mobile.MobilePhone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MobilePhone>
        PARSER = new com.google.protobuf.AbstractParser<MobilePhone>() {
      public MobilePhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MobilePhone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MobilePhone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MobilePhone> getParserForType() {
      return PARSER;
    }

    public com.pb.Mobile.MobilePhone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HardWareOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HardWare)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rom = 1;</code>
     */
    boolean hasRom();
    /**
     * <code>required int32 rom = 1;</code>
     */
    int getRom();

    /**
     * <code>required int32 ram = 2;</code>
     */
    boolean hasRam();
    /**
     * <code>required int32 ram = 2;</code>
     */
    int getRam();

    /**
     * <code>required int32 size = 3;</code>
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 3;</code>
     */
    int getSize();
  }
  /**
   * Protobuf type {@code HardWare}
   */
  public  static final class HardWare extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HardWare)
      HardWareOrBuilder {
    // Use HardWare.newBuilder() to construct.
    private HardWare(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HardWare() {
      rom_ = 0;
      ram_ = 0;
      size_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    @SuppressWarnings("unused")
	private HardWare(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rom_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ram_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pb.Mobile.internal_static_HardWare_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pb.Mobile.internal_static_HardWare_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pb.Mobile.HardWare.class, com.pb.Mobile.HardWare.Builder.class);
    }

    private int bitField0_;
    public static final int ROM_FIELD_NUMBER = 1;
    private int rom_;
    /**
     * <code>required int32 rom = 1;</code>
     */
    public boolean hasRom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rom = 1;</code>
     */
    public int getRom() {
      return rom_;
    }

    public static final int RAM_FIELD_NUMBER = 2;
    private int ram_;
    /**
     * <code>required int32 ram = 2;</code>
     */
    public boolean hasRam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 ram = 2;</code>
     */
    public int getRam() {
      return ram_;
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>required int32 size = 3;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ram_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, size_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ram_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pb.Mobile.HardWare)) {
        return super.equals(obj);
      }
      com.pb.Mobile.HardWare other = (com.pb.Mobile.HardWare) obj;

      boolean result = true;
      result = result && (hasRom() == other.hasRom());
      if (hasRom()) {
        result = result && (getRom()
            == other.getRom());
      }
      result = result && (hasRam() == other.hasRam());
      if (hasRam()) {
        result = result && (getRam()
            == other.getRam());
      }
      result = result && (hasSize() == other.hasSize());
      if (hasSize()) {
        result = result && (getSize()
            == other.getSize());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRom()) {
        hash = (37 * hash) + ROM_FIELD_NUMBER;
        hash = (53 * hash) + getRom();
      }
      if (hasRam()) {
        hash = (37 * hash) + RAM_FIELD_NUMBER;
        hash = (53 * hash) + getRam();
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pb.Mobile.HardWare parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pb.Mobile.HardWare parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pb.Mobile.HardWare parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pb.Mobile.HardWare parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pb.Mobile.HardWare parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pb.Mobile.HardWare parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pb.Mobile.HardWare prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HardWare}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HardWare)
        com.pb.Mobile.HardWareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pb.Mobile.internal_static_HardWare_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pb.Mobile.internal_static_HardWare_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pb.Mobile.HardWare.class, com.pb.Mobile.HardWare.Builder.class);
      }

      // Construct using com.pb.Mobile.HardWare.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ram_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pb.Mobile.internal_static_HardWare_descriptor;
      }

      public com.pb.Mobile.HardWare getDefaultInstanceForType() {
        return com.pb.Mobile.HardWare.getDefaultInstance();
      }

      public com.pb.Mobile.HardWare build() {
        com.pb.Mobile.HardWare result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pb.Mobile.HardWare buildPartial() {
        com.pb.Mobile.HardWare result = new com.pb.Mobile.HardWare(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rom_ = rom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ram_ = ram_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pb.Mobile.HardWare) {
          return mergeFrom((com.pb.Mobile.HardWare)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pb.Mobile.HardWare other) {
        if (other == com.pb.Mobile.HardWare.getDefaultInstance()) return this;
        if (other.hasRom()) {
          setRom(other.getRom());
        }
        if (other.hasRam()) {
          setRam(other.getRam());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRom()) {
          return false;
        }
        if (!hasRam()) {
          return false;
        }
        if (!hasSize()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pb.Mobile.HardWare parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pb.Mobile.HardWare) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rom_ ;
      /**
       * <code>required int32 rom = 1;</code>
       */
      public boolean hasRom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rom = 1;</code>
       */
      public int getRom() {
        return rom_;
      }
      /**
       * <code>required int32 rom = 1;</code>
       */
      public Builder setRom(int value) {
        bitField0_ |= 0x00000001;
        rom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rom = 1;</code>
       */
      public Builder clearRom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rom_ = 0;
        onChanged();
        return this;
      }

      private int ram_ ;
      /**
       * <code>required int32 ram = 2;</code>
       */
      public boolean hasRam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 ram = 2;</code>
       */
      public int getRam() {
        return ram_;
      }
      /**
       * <code>required int32 ram = 2;</code>
       */
      public Builder setRam(int value) {
        bitField0_ |= 0x00000002;
        ram_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ram = 2;</code>
       */
      public Builder clearRam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ram_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>required int32 size = 3;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 size = 3;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 3;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 3;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HardWare)
    }

    // @@protoc_insertion_point(class_scope:HardWare)
    private static final com.pb.Mobile.HardWare DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pb.Mobile.HardWare();
    }

    public static com.pb.Mobile.HardWare getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HardWare>
        PARSER = new com.google.protobuf.AbstractParser<HardWare>() {
      public HardWare parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HardWare(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HardWare> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HardWare> getParserForType() {
      return PARSER;
    }

    public com.pb.Mobile.HardWare getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MobilePhone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MobilePhone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HardWare_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HardWare_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\"K\n\013MobilePhone\022\r\n\005brand\030\001" +
      " \002(\t\022\033\n\010hardWare\030\002 \002(\0132\t.HardWare\022\020\n\010sof" +
      "tware\030\003 \003(\t\"2\n\010HardWare\022\013\n\003rom\030\001 \002(\005\022\013\n\003" +
      "ram\030\002 \002(\005\022\014\n\004size\030\003 \002(\005B\010\n\006com.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MobilePhone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MobilePhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MobilePhone_descriptor,
        new java.lang.String[] { "Brand", "HardWare", "Software", });
    internal_static_HardWare_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HardWare_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HardWare_descriptor,
        new java.lang.String[] { "Rom", "Ram", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
