// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/mobile.proto

package com.pb;

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MobilePhoneOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string brand = 1;
    boolean hasBrand();
    String getBrand();
    
    // required .HardWare hardWare = 2;
    boolean hasHardWare();
    com.pb.Mobile.HardWare getHardWare();
    com.pb.Mobile.HardWareOrBuilder getHardWareOrBuilder();
    
    // repeated string software = 3;
    java.util.List<String> getSoftwareList();
    int getSoftwareCount();
    String getSoftware(int index);
  }
  public static final class MobilePhone extends
      com.google.protobuf.GeneratedMessage
      implements MobilePhoneOrBuilder {
    // Use MobilePhone.newBuilder() to construct.
    private MobilePhone(Builder builder) {
      super(builder);
    }
    private MobilePhone(boolean noInit) {}
    
    private static final MobilePhone defaultInstance;
    public static MobilePhone getDefaultInstance() {
      return defaultInstance;
    }
    
    public MobilePhone getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pb.Mobile.internal_static_MobilePhone_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pb.Mobile.internal_static_MobilePhone_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string brand = 1;
    public static final int BRAND_FIELD_NUMBER = 1;
    private java.lang.Object brand_;
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          brand_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .HardWare hardWare = 2;
    public static final int HARDWARE_FIELD_NUMBER = 2;
    private com.pb.Mobile.HardWare hardWare_;
    public boolean hasHardWare() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.pb.Mobile.HardWare getHardWare() {
      return hardWare_;
    }
    public com.pb.Mobile.HardWareOrBuilder getHardWareOrBuilder() {
      return hardWare_;
    }
    
    // repeated string software = 3;
    public static final int SOFTWARE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList software_;
    public java.util.List<String>
        getSoftwareList() {
      return software_;
    }
    public int getSoftwareCount() {
      return software_.size();
    }
    public String getSoftware(int index) {
      return software_.get(index);
    }
    
    private void initFields() {
      brand_ = "";
      hardWare_ = com.pb.Mobile.HardWare.getDefaultInstance();
      software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHardWare()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHardWare().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, hardWare_);
      }
      for (int i = 0; i < software_.size(); i++) {
        output.writeBytes(3, software_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, hardWare_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < software_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(software_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSoftwareList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pb.Mobile.MobilePhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pb.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pb.Mobile.MobilePhone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pb.Mobile.MobilePhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pb.Mobile.internal_static_MobilePhone_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pb.Mobile.internal_static_MobilePhone_fieldAccessorTable;
      }
      
      // Construct using com.pb.Mobile.MobilePhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHardWareFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hardWareBuilder_ == null) {
          hardWare_ = com.pb.Mobile.HardWare.getDefaultInstance();
        } else {
          hardWareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pb.Mobile.MobilePhone.getDescriptor();
      }
      
      public com.pb.Mobile.MobilePhone getDefaultInstanceForType() {
        return com.pb.Mobile.MobilePhone.getDefaultInstance();
      }
      
      public com.pb.Mobile.MobilePhone build() {
        com.pb.Mobile.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pb.Mobile.MobilePhone buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pb.Mobile.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pb.Mobile.MobilePhone buildPartial() {
        com.pb.Mobile.MobilePhone result = new com.pb.Mobile.MobilePhone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (hardWareBuilder_ == null) {
          result.hardWare_ = hardWare_;
        } else {
          result.hardWare_ = hardWareBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = new com.google.protobuf.UnmodifiableLazyStringList(
              software_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.software_ = software_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pb.Mobile.MobilePhone) {
          return mergeFrom((com.pb.Mobile.MobilePhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pb.Mobile.MobilePhone other) {
        if (other == com.pb.Mobile.MobilePhone.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          setBrand(other.getBrand());
        }
        if (other.hasHardWare()) {
          mergeHardWare(other.getHardWare());
        }
        if (!other.software_.isEmpty()) {
          if (software_.isEmpty()) {
            software_ = other.software_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSoftwareIsMutable();
            software_.addAll(other.software_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBrand()) {
          
          return false;
        }
        if (!hasHardWare()) {
          
          return false;
        }
        if (!getHardWare().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              brand_ = input.readBytes();
              break;
            }
            case 18: {
              com.pb.Mobile.HardWare.Builder subBuilder = com.pb.Mobile.HardWare.newBuilder();
              if (hasHardWare()) {
                subBuilder.mergeFrom(getHardWare());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHardWare(subBuilder.buildPartial());
              break;
            }
            case 26: {
              ensureSoftwareIsMutable();
              software_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string brand = 1;
      private java.lang.Object brand_ = "";
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBrand(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      void setBrand(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
      }
      
      // required .HardWare hardWare = 2;
      private com.pb.Mobile.HardWare hardWare_ = com.pb.Mobile.HardWare.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pb.Mobile.HardWare, com.pb.Mobile.HardWare.Builder, com.pb.Mobile.HardWareOrBuilder> hardWareBuilder_;
      public boolean hasHardWare() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.pb.Mobile.HardWare getHardWare() {
        if (hardWareBuilder_ == null) {
          return hardWare_;
        } else {
          return hardWareBuilder_.getMessage();
        }
      }
      public Builder setHardWare(com.pb.Mobile.HardWare value) {
        if (hardWareBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hardWare_ = value;
          onChanged();
        } else {
          hardWareBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setHardWare(
          com.pb.Mobile.HardWare.Builder builderForValue) {
        if (hardWareBuilder_ == null) {
          hardWare_ = builderForValue.build();
          onChanged();
        } else {
          hardWareBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeHardWare(com.pb.Mobile.HardWare value) {
        if (hardWareBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              hardWare_ != com.pb.Mobile.HardWare.getDefaultInstance()) {
            hardWare_ =
              com.pb.Mobile.HardWare.newBuilder(hardWare_).mergeFrom(value).buildPartial();
          } else {
            hardWare_ = value;
          }
          onChanged();
        } else {
          hardWareBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearHardWare() {
        if (hardWareBuilder_ == null) {
          hardWare_ = com.pb.Mobile.HardWare.getDefaultInstance();
          onChanged();
        } else {
          hardWareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.pb.Mobile.HardWare.Builder getHardWareBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHardWareFieldBuilder().getBuilder();
      }
      public com.pb.Mobile.HardWareOrBuilder getHardWareOrBuilder() {
        if (hardWareBuilder_ != null) {
          return hardWareBuilder_.getMessageOrBuilder();
        } else {
          return hardWare_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.pb.Mobile.HardWare, com.pb.Mobile.HardWare.Builder, com.pb.Mobile.HardWareOrBuilder> 
          getHardWareFieldBuilder() {
        if (hardWareBuilder_ == null) {
          hardWareBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pb.Mobile.HardWare, com.pb.Mobile.HardWare.Builder, com.pb.Mobile.HardWareOrBuilder>(
                  hardWare_,
                  getParentForChildren(),
                  isClean());
          hardWare_ = null;
        }
        return hardWareBuilder_;
      }
      
      // repeated string software = 3;
      private com.google.protobuf.LazyStringList software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSoftwareIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = new com.google.protobuf.LazyStringArrayList(software_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getSoftwareList() {
        return java.util.Collections.unmodifiableList(software_);
      }
      public int getSoftwareCount() {
        return software_.size();
      }
      public String getSoftware(int index) {
        return software_.get(index);
      }
      public Builder setSoftware(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addSoftware(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllSoftware(
          java.lang.Iterable<String> values) {
        ensureSoftwareIsMutable();
        super.addAll(values, software_);
        onChanged();
        return this;
      }
      public Builder clearSoftware() {
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addSoftware(com.google.protobuf.ByteString value) {
        ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:MobilePhone)
    }
    
    static {
      defaultInstance = new MobilePhone(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MobilePhone)
  }
  
  public interface HardWareOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 rom = 1;
    boolean hasRom();
    int getRom();
    
    // required int32 ram = 2;
    boolean hasRam();
    int getRam();
    
    // required int32 size = 3;
    boolean hasSize();
    int getSize();
  }
  public static final class HardWare extends
      com.google.protobuf.GeneratedMessage
      implements HardWareOrBuilder {
    // Use HardWare.newBuilder() to construct.
    private HardWare(Builder builder) {
      super(builder);
    }
    private HardWare(boolean noInit) {}
    
    private static final HardWare defaultInstance;
    public static HardWare getDefaultInstance() {
      return defaultInstance;
    }
    
    public HardWare getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pb.Mobile.internal_static_HardWare_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pb.Mobile.internal_static_HardWare_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 rom = 1;
    public static final int ROM_FIELD_NUMBER = 1;
    private int rom_;
    public boolean hasRom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRom() {
      return rom_;
    }
    
    // required int32 ram = 2;
    public static final int RAM_FIELD_NUMBER = 2;
    private int ram_;
    public boolean hasRam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRam() {
      return ram_;
    }
    
    // required int32 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSize() {
      return size_;
    }
    
    private void initFields() {
      rom_ = 0;
      ram_ = 0;
      size_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ram_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, size_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ram_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pb.Mobile.HardWare parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pb.Mobile.HardWare parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pb.Mobile.HardWare parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pb.Mobile.HardWare parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pb.Mobile.HardWare parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pb.Mobile.HardWare parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pb.Mobile.HardWare parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pb.Mobile.HardWare prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pb.Mobile.HardWareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pb.Mobile.internal_static_HardWare_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pb.Mobile.internal_static_HardWare_fieldAccessorTable;
      }
      
      // Construct using com.pb.Mobile.HardWare.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        rom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ram_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pb.Mobile.HardWare.getDescriptor();
      }
      
      public com.pb.Mobile.HardWare getDefaultInstanceForType() {
        return com.pb.Mobile.HardWare.getDefaultInstance();
      }
      
      public com.pb.Mobile.HardWare build() {
        com.pb.Mobile.HardWare result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pb.Mobile.HardWare buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pb.Mobile.HardWare result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pb.Mobile.HardWare buildPartial() {
        com.pb.Mobile.HardWare result = new com.pb.Mobile.HardWare(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rom_ = rom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ram_ = ram_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pb.Mobile.HardWare) {
          return mergeFrom((com.pb.Mobile.HardWare)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pb.Mobile.HardWare other) {
        if (other == com.pb.Mobile.HardWare.getDefaultInstance()) return this;
        if (other.hasRom()) {
          setRom(other.getRom());
        }
        if (other.hasRam()) {
          setRam(other.getRam());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRom()) {
          
          return false;
        }
        if (!hasRam()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rom_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ram_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 rom = 1;
      private int rom_ ;
      public boolean hasRom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRom() {
        return rom_;
      }
      public Builder setRom(int value) {
        bitField0_ |= 0x00000001;
        rom_ = value;
        onChanged();
        return this;
      }
      public Builder clearRom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rom_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 ram = 2;
      private int ram_ ;
      public boolean hasRam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRam() {
        return ram_;
      }
      public Builder setRam(int value) {
        bitField0_ |= 0x00000002;
        ram_ = value;
        onChanged();
        return this;
      }
      public Builder clearRam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ram_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 size = 3;
      private int size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSize() {
        return size_;
      }
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:HardWare)
    }
    
    static {
      defaultInstance = new HardWare(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HardWare)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MobilePhone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MobilePhone_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HardWare_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HardWare_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/mobile.proto\"K\n\013MobilePhone\022\r\n\005b" +
      "rand\030\001 \002(\t\022\033\n\010hardWare\030\002 \002(\0132\t.HardWare\022" +
      "\020\n\010software\030\003 \003(\t\"2\n\010HardWare\022\013\n\003rom\030\001 \002" +
      "(\005\022\013\n\003ram\030\002 \002(\005\022\014\n\004size\030\003 \002(\005B\010\n\006com.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MobilePhone_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MobilePhone_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MobilePhone_descriptor,
              new java.lang.String[] { "Brand", "HardWare", "Software", },
              com.pb.Mobile.MobilePhone.class,
              com.pb.Mobile.MobilePhone.Builder.class);
          internal_static_HardWare_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HardWare_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HardWare_descriptor,
              new java.lang.String[] { "Rom", "Ram", "Size", },
              com.pb.Mobile.HardWare.class,
              com.pb.Mobile.HardWare.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
